- name: Linux Everything Except Cred Rolls and Breakglass
  hosts: linux
  vars_files:
    - vars/management.yml
  ignore_errors: yes
  roles:
    - {role: linux_init_config, ignore_errors: yes}
    - {role: linux_osquery, ignore_errors: yes}
    - {role: linux_backup, ignore_errors: yes}
    - {role: linux_patch, ignore_errors: yes}
    - {role: linux_harden, ignore_errors: yes}
    - {role: linux_ufw, ignore_errors: yes}
    - {role: linux_graylog, ignore_errors: yes}
    - {role: linux_immutable, ignore_errors: yes}
